channels:
- conda-forge
dependencies:
- python=3.9.7
- pip<=21.2.4
- pip:
  - mlflow==2.3
  - cloudpickle==1.6.0
  - numpy==1.24.3
  - psutil==5.8.0
  - scikit-learn==1.2.2
  - scipy==1.9.1
name: mlflow-env
